# Kafka sink configuration for fraud alerts
# Flat structure with dot-notation properties

# Sink type (required)
type: "kafka_sink"

# Kafka connection properties
bootstrap.servers: "localhost:9092"
topic: "fraud-alerts"

# Producer settings
value.format: "json"
key.format: "string"
batch.size: 4096
linger.ms: 1
compression.type: "lz4"
acks: "all"
retries: 5
retry.backoff.ms: 2000
enable.idempotence: true

# Error handling
failure_strategy: "RetryWithBackoff"
max_retries: 5
timeout_ms: 30000