# Kafka sink configuration for processing metrics
# Flat structure with dot-notation properties

# Sink type (required)
type: "kafka_sink"

# Kafka connection properties
bootstrap.servers: "localhost:9092"
topic: "processing-metrics"

# Producer settings
value.format: "json"
key.format: "string"
batch.size: 4096
linger.ms: 15
compression.type: "gzip"
acks: "all"
retries: 3
retry.backoff.ms: 100
enable.idempotence: true

# Error handling
failure_strategy: "LogAndContinue"
max_retries: 3
timeout_ms: 30000