[package]
name = "ferrisstreams"
version = "0.1.0"
edition = "2024"

[dependencies]
pretty_env_logger = "0.5.0"
log = "0.4.27"
env_logger = "0.11.8"
rdkafka = "0.38.0"
tokio = { version = "1.46.1", features = ["full"] }
chrono = "0.4.41"
uuid = { version = "1.17.0", features = ["v4"] }
logtest = "2.0.0"
futures = "0.3"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0.69"

# Optional dependencies for additional serialization formats
apache-avro = { version = "0.16.0", optional = true }
prost = { version = "0.14.1", optional = true }
bincode = { version = "1.3.3", optional = true }

[dev-dependencies]
serial_test = "2.0.0"
crossbeam-queue = "0.3"
tokio-stream = "0.1"

[features]
default = ["json", "protobuf", "avro"]
json = []
avro = ["apache-avro"]
protobuf = ["prost"]

# Performance examples - organized in subfolder
[[example]]
name = "json_performance_test"
path = "examples/performance/json_performance_test.rs"

[[example]]
name = "raw_bytes_performance_test"
path = "examples/performance/raw_bytes_performance_test.rs"

[[example]]
name = "latency_performance_test"
path = "examples/performance/latency_performance_test.rs"

[[example]]
name = "simple_zero_copy_test"
path = "examples/performance/simple_zero_copy_test.rs"

[[example]]
name = "simple_async_optimization_test"
path = "examples/performance/simple_async_optimization_test.rs"

[[example]]
name = "resource_monitoring_test"
path = "examples/performance/resource_monitoring_test.rs"
