[package]
name = "ferrisstreams"
version = "0.1.0"
edition = "2024"

[dependencies]
pretty_env_logger = "0.5.0"
log = "0.4.27"
env_logger = "0.11.8"
rdkafka = "0.38.0"
tokio = { version = "1.46.1", features = ["full"] }
chrono = "0.4.41"
uuid = { version = "1.17.0", features = ["v4"] }
logtest = "2.0.0"
futures = "0.3"
