# Prometheus configuration for FerrisStreams Demo monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them  
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# Scrape configuration
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Kafka JMX metrics
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9101']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # FerrisStreams application metrics (if exposed)
  - job_name: 'ferrisstreams'
    static_configs:
      - targets: ['host.docker.internal:8888']  # Adjust port as needed
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 5s

  # Schema Registry metrics  
  - job_name: 'schema-registry'
    static_configs:
      - targets: ['schema-registry:8081']
    metrics_path: /metrics
    scrape_interval: 30s

  # Kafka Connect metrics
  - job_name: 'kafka-connect'
    static_configs:
      - targets: ['kafka-connect:8083']
    metrics_path: /metrics  
    scrape_interval: 30s

  # Redis metrics (if redis-exporter is added)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: /metrics
    scrape_interval: 30s

  # Node exporter for system metrics (if added)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

# Custom recording rules for FerrisStreams metrics
recording_rules:
  - name: ferrisstreams_aggregations
    rules:
      # Calculate processing rate over 5 minutes
      - record: ferrisstreams:processing_rate_5m
        expr: rate(ferrisstreams_records_processed_total[5m])
        
      # Calculate error rate percentage
      - record: ferrisstreams:error_rate_percent_5m  
        expr: rate(ferrisstreams_errors_total[5m]) / rate(ferrisstreams_records_processed_total[5m]) * 100
        
      # Average processing latency
      - record: ferrisstreams:avg_latency_5m
        expr: rate(ferrisstreams_processing_latency_seconds_sum[5m]) / rate(ferrisstreams_processing_latency_seconds_count[5m])

# Alerting rules for demo monitoring
alerting_rules:
  - name: ferrisstreams_alerts
    rules:
      # High error rate alert
      - alert: HighErrorRate
        expr: ferrisstreams:error_rate_percent_5m > 5
        for: 2m
        labels:
          severity: warning
          service: ferrisstreams
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }}% over the last 5 minutes"
          
      # Low throughput alert  
      - alert: LowThroughput
        expr: ferrisstreams:processing_rate_5m < 10
        for: 5m
        labels:
          severity: warning
          service: ferrisstreams
        annotations:
          summary: "Low processing throughput"
          description: "Processing rate is {{ $value }} records/sec"
          
      # High processing latency
      - alert: HighLatency
        expr: ferrisstreams:avg_latency_5m > 0.1  # 100ms
        for: 3m
        labels:
          severity: warning  
          service: ferrisstreams
        annotations:
          summary: "High processing latency"
          description: "Average latency is {{ $value }}s over the last 5 minutes"

# Remote write configuration (for production)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint"
#     basic_auth:
#       username: "user"
#       password: "password"