# Common Kafka Data Source Configuration for Examples
# Base configuration for all Kafka data sources
# URIs are constructed as: kafka://{bootstrap_servers}/{topic_name}

datasource:
  type: kafka
  
  # Standard consumer configuration
  consumer_config:
    bootstrap_servers: "localhost:9092"
    auto_offset_reset: "latest"
    enable_auto_commit: true
    auto_commit_interval_ms: 100
    session_timeout_ms: 6000
    heartbeat_interval_ms: 2000
    
  # Common schema settings
  schema:
    key_format: string
    value_format: json
    
    # Schema Registry settings (for Avro/Protobuf)
    registry_url: "http://localhost:8081"
    # registry_username: "schema_user"
    # registry_password: "schema_pass"
    
    # Schema configuration examples (choose based on value_format)
    # For Avro format:
    # avro.schema: |
    #   {
    #     "type": "record",
    #     "name": "CommonRecord", 
    #     "fields": [
    #       {"name": "id", "type": "string"},
    #       {"name": "timestamp", "type": "long"},
    #       {"name": "payload", "type": "string"}
    #     ]
    #   }
    #
    # For Protobuf format:  
    # protobuf.schema: |
    #   syntax = "proto3";
    #   message CommonRecord {
    #     string id = 1;
    #     int64 timestamp = 2;
    #     string payload = 3;
    #   }
    #
    # Schema file alternatives:
    # avro.schema.file: "./schemas/common_record.avsc"  
    # protobuf.schema.file: "./schemas/common_record.proto"
    
  # Default performance settings
  performance:
    compression_type: "gzip"
    
  # Default stream properties
  stream_config:
    replication_factor: 1  # Single node for examples
    cleanup_policy: "delete"
    
# Performance profiles that can be referenced
performance_profiles:
  low_latency:
    fetch_max_wait_ms: 10
    max_poll_records: 500
    buffer_size: 32768
    
  high_throughput:
    fetch_max_wait_ms: 100
    max_poll_records: 2000
    buffer_size: 131072
    
  balanced:
    fetch_max_wait_ms: 50
    max_poll_records: 1000
    buffer_size: 65536