# Fraud Detection Output Configuration
# Critical fraud alerts

extends: common_kafka_sink.yaml

topic:
  name: "fraud_alerts"
  
delivery_profile: critical

topic_config:
  partitions: 8
  replication_factor: 3
  retention_ms: 7776000000  # 90 days retention for compliance
  
metadata:
  description: "Fraud detection alerts"
  data_classification: "security_critical"
  priority: "critical"