# Orders Topic Configuration
# E-commerce orders data source

extends: common_kafka_source.yaml

topic:
  name: "orders"
  
consumer_group: "ecommerce_analytics_group"
performance_profile: balanced

datasource:
  schema:
    key_field: customer_id

topic_config:
  partitions: 4
  retention_ms: 604800000  # 7 days retention
  
metadata:
  description: "E-commerce orders stream"
  data_classification: "business_critical"
  update_frequency: "real_time"