# Sensor Data Topic Configuration
# Real-time IoT sensor readings

extends: common_kafka_source.yaml

topic:
  name: "sensor_data"
  
consumer_group: "iot_monitoring_group"
performance_profile: high_throughput

datasource:
  schema:
    key_field: device_id
    
topic_config:
  partitions: 12
  retention_ms: 2592000000  # 30 days retention
  
metadata:
  description: "IoT sensor data stream"
  data_classification: "sensor_telemetry"
  update_frequency: "real_time"