name: Quick Check

on:
  push:
    branches: [ main, develop, master ]
  pull_request:
    branches: [ main, develop, master ]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0  # Disable incremental compilation for CI
  CARGO_PROFILE_DEV_DEBUG: 0  # Reduce debug info size
  RUST_BACKTRACE: 1

jobs:
  quick-check:
    name: Quick Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Rust Environment
      uses: ./.github/actions/setup-rust
      with:
        rust-version: stable
        components: rustfmt,clippy
        cache-suffix: quick

    - name: Check formatting
      run: cargo fmt --all -- --check

    - name: Check compilation
      run: cargo check --all-targets

    - name: Run clippy
      run: cargo clippy --all-targets

    - name: Build project
      run: cargo build

    - name: Run unit tests
      run: cargo test --lib

    - name: Test examples compile
      run: |
        cargo check --example builder_configuration
        cargo check --example consumer_with_headers
        cargo check --example fluent_api_example
        cargo check --example headers_example
        cargo check --example message_metadata_example  
        cargo check --example typed_kafka_example
        # Performance examples
        cargo check --example json_performance_test
        cargo check --example raw_bytes_performance_test
        cargo check --example latency_performance_test
        cargo check --example simple_zero_copy_test
        cargo check --example simple_async_optimization_test
        cargo check --example resource_monitoring_test

    - name: Validate configuration schemas
      run: |
        echo "🔧 Generating JSON schemas for validation..."
        cargo run --bin ferris-schema-generator --no-default-features
        
        echo "🔍 Checking schema consistency..."
        if ! diff -u ferrisstreams-config.schema.json ferrisstreams-config.schema.json.expected; then
          echo "❌ Schema validation failed - generated schema differs from committed version!"
          echo "Run: cargo run --bin ferris-schema-generator --no-default-features"
          echo "Then commit the updated schema files."
          exit 1
        fi
        
        echo "✅ Schema validation passed!"